SLAVE_SINGLE_REAL = 0
SLAVE_DIVERSE_REAL = 2
SLAVE_SINGLE_COMPLEX = 4
MASTER_SINGLE_REAL = 8
MASTER_DIVERSE_REAL = 10
MASTER_SINGLE_COMPLEX = 12

NCO_BYPASS = 1
NCO_ACTIVE_PD = 2
NCO_ACTIVE_AD = 4
NCO_ACTIVE_PAD = 6

D300_OPT = [
    'SLAVE SINGLE REAL',
    'SLAVE DIVERSE REAL',
    'SLAVE SINGLE COMPLEX',
    'MASTER SINGLE REAL',
    'MASTER DIVERSE REAL',
    'MASTER SINGLE COMPLEX'
    ]

D300_DCT = {
    'SLAVE SINGLE REAL': SLAVE_SINGLE_REAL,
    'SLAVE DIVERSE REAL': SLAVE_DIVERSE_REAL,
    'SLAVE SINGLE COMPLEX': SLAVE_SINGLE_COMPLEX,
    'MASTER SINGLE REAL': MASTER_SINGLE_REAL,
    'MASTER DIVERSE REAL': MASTER_DIVERSE_REAL,
    'MASTER SINGLE COMPLEX': MASTER_SINGLE_COMPLEX
    }

D301_OPT = [
    'NCO BYPASS',
    'NCO ACTIVE PD',
    'NCO ACTIVE AD',
    'NCO ACTIVE PAD'
    ]

D301_DCT = {
    'NCO BYPASS': NCO_BYPASS,
    'NCO ACTIVE PD': NCO_ACTIVE_PD,
    'NCO ACTIVE AD': NCO_ACTIVE_AD,
    'NCO ACTIVE PAD': NCO_ACTIVE_PAD
    }

D302_DCT = {
    'MAX': 4_294_967_295,
    'DEFAULT': 4_294_967_295
}

D303_DCT = {
    'MAX': 4_294_967_295,
    'DEFAULT': 85_899_346
}

D304_DCT = {
    'MAX': 65_535,
    'DEFAULT': 0
}

D305_DCT = {
    'MAX': 6,
    'DEFAULT': 0
    #  TODO 1 << 2
}

D306_DCT = {
    'MAX': 15,
    'DEFAULT': 0
}

D307_DCT = {
    'MAX': 20
}

D308_DCT = {
    'MAX': 31
}

D309_DCT = {
    'MAX': 31
}

D30A_DCT = {
    'MAX': 31
}
